name: hexlet-ci-app
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: "Installing build:"
        run: make setup
      - name: "Installing dependencies:"
        run: make install
      - name: "Running tests:"
        run: make tests
      - name: "Running linter:"
        run: make lint
